# An example of ClusterConfig showing nodegroups with mixed instances (spot and on demand):
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: eksworkshop-eksctl
    region: eu-west-1



managedNodeGroups:
    - name: dolphins
      instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
      labels: {role: worker}
      minSize: 2
      maxSize: 10
      desiredCapacity: 2
      spot: true
      ssh:
        enableSsm: true

      tags:
        auto-delete: "no"
        workload: eksworkshop

nodeGroups:
    - name: dolphins
      labels: {role: worker}
      minSize: 2
      maxSize: 8
      desiredCapacity: 2
      instancesDistribution:
        maxPrice: 0.017
        instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        spotInstancePools: 2      
      ssh:
        enableSsm: true

      tags:
        auto-delete: "no"
        workload: eksworkshop        